#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "4zq6uj-maxwardle-ocp201-tst-tools"
def DEV_NAMESPACE = "4zq6uj-maxwardle-ocp201-tst-dev"
def PROD_NAMESPACE = "4zq6uj-maxwardle-ocp201-tst-prod"


//Pipeline
node {
    stage ('Deploy Loki to Dev'){
        dir ('simple_pipeline') {
            checkout scm
            sh "oc process -f openshift201/templates/loki_template.yaml | oc apply -f - -n ${DEV_NAMESPACE}"

        }
    }
}


